
#ifndef RHI_CONFIG_H
#define RHI_CONFIG_H

// Rhi related
#define RHI_MAX_FRAMES_IN_FLIGHT 3
#define RHI_DEFAULT_STAGING_HEAP_SIZE_MB 64

// vulkan related
#define RHI_VULKAN_API_VERSION VK_API_VERSION_1_3
#define RHI_VULKAN_PROFILE_NAME VP_KHR_ROADMAP_2024_NAME
#define RHI_VULKAN_PROFILE_SPEC_VERSION VP_KHR_ROADMAP_2024_SPEC_VERSION
#define RHI_VULKAN_PROFILE_MIN_API_VERSION VP_KHR_ROADMAP_2024_MIN_API_VERSION

#endif
